name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Build Flutter web (from flutter_app/)
      - name: Build Flutter web
        working-directory: ./flutter_app
        run: |
          flutter pub get
          flutter build web --release

      # Install Cloud Functions deps (only if deploying Functions)
      - name: Install functions deps
        working-directory: ./functions
        run: npm ci

      # Deploy with Firebase CLI
      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Deploy Hosting (+ Functions if needed)
        working-directory: .
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          # Hosting only
          firebase deploy --only hosting --project rule-post --non-interactive
          # OR, if you changed functions as well:
          # firebase deploy --only functions,hosting --project rule-post --non-interactive
