name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ⬇️ Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # ⬇️ Build Flutter web (ensure firebase.json -> "public": "flutter_app/build/web")
      - name: Build Flutter web
        working-directory: ./flutter_app
        run: |
          flutter pub get
          flutter build web --release

      # (Optional) Install Functions deps if you deploy functions
      - name: Install functions deps
        if: always()
        working-directory: ./functions
        run: npm ci

      # ⬇️ Authenticate with GCP using a service account JSON in a GitHub Secret
      - id: auth
        name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RULE_POST }}

      # Hosting (prod)
      - name: Deploy Hosting (live channel)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RULE_POST }}
          channelId: live
          projectId: rule-post

      # ── OPTIONAL: Deploy Cloud Functions (prod) ──────────────────────────
      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      # ✅ Ensure secret exists/enabled for this project (creates a new version if needed)
      # Put your Resend key in GitHub Secrets as RESEND_API_KEY
      - name: Ensure RESEND_API_KEY is set in Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: |
          echo -n "$RESEND_API_KEY" | npx firebase-tools@latest functions:secrets:set RESEND_API_KEY --project rule-post --force

      - name: Deploy Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: npx firebase-tools@latest deploy --only functions --project rule-post --non-interactive
