name: Deploy to Firebase Hosting preview on PR
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ⬇️ Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # ⬇️ Build Flutter web (same as merge)
      - name: Build Flutter web
        working-directory: ./flutter_app
        run: |
          flutter pub get
          flutter build web --release

      # (Optional) Install Functions deps if you preview functions separately (usually skip)
      - name: Install functions deps
        if: false
        working-directory: ./functions
        run: npm ci

      # ⬇️ Auth (same service account)
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RULE_POST }}

      # Hosting preview — channel per PR number (auto cleaned up by Firebase)
      - name: Deploy Hosting Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RULE_POST }}
          projectId: rule-post
          channelId: pr-${{ github.event.number }}
