name: Deploy to Firebase Hosting on merge
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # Build Flutter web (from flutter_app/)
      - name: Build Flutter web
        working-directory: ./flutter_app
        run: |
          flutter pub get
          flutter build web --release

      # Install Cloud Functions deps (optional: only needed if you also deploy Functions)
      - name: Install functions deps
        working-directory: ./functions
        run: npm ci

      # Deploy Hosting with service account (no FIREBASE_TOKEN needed)
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RULE_POST }}
          channelId: live
          projectId: rule-post

      # ── OPTIONAL: Deploy Cloud Functions too ─────────────────────────────
      # If you want to deploy Functions in the same workflow:
      # 1) Create a FIREBASE_TOKEN secret (run `firebase login:ci` locally).
      # 2) Uncomment the three steps below.

      - name: Install Firebase CLI
        run: npm i -g firebase-tools
      
      - name: Deploy Functions (CLI)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
        run: firebase deploy --only functions --project rule-post --non-interactive
